name: Build LaTeX document

on:
  pull_request:
  workflow_dispatch:
  push:
    tags:
      - "*"
    branches:
      - main

jobs:
  build_latex:
    name: Build the LaTeX CV
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: SAMUEL-LOPEZ.tex
          working_directory: src/cv
          args: -pdf -file-line-error -halt-on-error -interaction=nonstopmode -outdir=out

      - name: Copy generated files to a new directory
        run: |
          mkdir -p output
          cp -r src/cv/out/* output/

      - name: Disable Jekyll for GitHub Pages
        run: echo > output/.nojekyll

      - name: Add a basic index.html
        run: |
          echo '<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Samuel López CV</title></head><body><h1>Samuel López CV</h1><p><a href="SAMUEL-LOPEZ.pdf">Download CV (PDF)</a></p></body></html>' > output/index.html

      - name: Upload PDF as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: SAMUEL-LOPEZ-CV
          path: output/SAMUEL-LOPEZ.pdf
          retention-days: 7

      - name: Deploy CV to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.6.9
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: output
          clean: true
          single-commit: true

      - name: Create a CV release
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./output/SAMUEL-LOPEZ.pdf